import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

const base = (p: string) => new URL(p, import.meta.url).pathname;
const migrationsDir = base("../db/migrations");
const outFile = base("../db/migrations.generated.ts");

const entries = readdirSync(migrationsDir)
	.filter((name) => statSync(join(migrationsDir, name)).isDirectory())
	.filter((name) =>
		statSync(join(migrationsDir, name, "migration.sql")).isFile(),
	)
	.sort();

const migrations = entries.map((name) => ({
	name,
	sql: readFileSync(join(migrationsDir, name, "migration.sql"), "utf-8"),
}));

const body = migrations
	.map(
		(m) =>
			`\t{ name: ${JSON.stringify(m.name)}, sql: ${JSON.stringify(m.sql)} },`,
	)
	.join("\n");

await Bun.write(
	outFile,
	`// AUTO-GENERATED by scripts/build-migrations.ts — do not edit.\n` +
		`export const migrations: { name: string; sql: string }[] = [\n${body}\n];\n`,
);

console.log(
	`Baked ${migrations.length} migration(s) into db/migrations.generated.ts`,
);
